version: '3.4'

services:
  tty-proxy:
    build:
      context: ./tty-proxy
    ports:
      - 3456:3456
      - 8080:8080
    environment:
      - "URL=http://${PUBLIC_URL}:8080"

  tty-share:
    depends_on:
      - "tty-proxy"
    build:
      context: ./tty-share
    tty: true
    cap_drop:
      - ALL
    volumes:
      - url:/app/url
    entrypoint: >
      sh -c "tty-share --tty-proxy ${PUBLIC_URL}:3456 --no-tls --public --readonly --command /bin/sh > app/url/link"

  srv:
    depends_on:
      - "tty-share"
    build:
      context: .
      network: host
    network_mode: host
    expose:
      - 25
    ports:
      - 5000:5000
    volumes:
      - url:/app/url
      - ./:/app
    environment:
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
    command: npm run debug

volumes:
  url: